apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd-secrets
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: git@github.com:gena-tokarev/infra.git
    targetRevision: main
    path: environments/development/argocd/secrets
    plugin:
      name: sops-yaml-v1
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    retry:
      limit: 10
      backoff: {duration: 10s, factor: 2, maxDuration: 3m}
    syncOptions: [PruneLast=true]
