apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: image-updater-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: platform
  source:
    repoURL: git@github.com:gt-engineering/infra.git
    targetRevision: main
    path: platform/image-updater
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    retry:
      limit: 20
      backoff: {duration: 10s, factor: 2, maxDuration: 3m}
    syncOptions: [CreateNamespace=true, ServerSideApply=true, PruneLast=true]
