apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - projects.yaml
  - gateway-api.yaml
  - cert-manager.yaml
  - platform-config.yaml
  - argocd.yaml
  - argocd-secrets.yaml
  - cortex-data.yaml
