apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: platform-config
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: git@github.com:gena-tokarev/infra.git
    targetRevision: main
    path: platform/config
  destination:
    server: https://kubernetes.default.svc
    namespace: gateway-system
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    retry:
      limit: 20
      backoff: {duration: 10s, factor: 2, maxDuration: 3m}
    syncOptions: [CreateNamespace=true, ServerSideApply=true, PruneLast=true]
