apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Cluster-level controllers and shared routing
  sourceRepos:
    - git@github.com:gt-engineering/infra.git
    - https://charts.jetstack.io
    - https://cloudnative-pg.github.io/charts
    - https://argoproj.github.io/argo-helm
    - https://github.com/kubernetes-sigs/gateway-api.git
  destinations:
    - namespace: '*'
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: workloads
  namespace: argocd
spec:
  description: Cortex and Podolog workloads
  sourceRepos:
    - git@github.com:gt-engineering/infra.git
  destinations:
    - namespace: cortex
      server: https://kubernetes.default.svc
    - namespace: podolog
      server: https://kubernetes.default.svc
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
