apiVersion: v1
kind: Secret
metadata:
  name: argocd-github-oauth
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: argocd
type: Opaque
stringData:
  dex.github.clientID: REPLACE_WITH_GITHUB_OAUTH_CLIENT_ID
  dex.github.clientSecret: REPLACE_WITH_GITHUB_OAUTH_CLIENT_SECRET
