apiVersion: v1
kind: ConfigMap
metadata:
  name: cortex-config
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  NODE_ENV: production
  {{- range $key, $value := .Values.config }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
